# 06 JUNE 2026

In [15]:
!python --version
!pip --version

Python 3.14.2
pip 24.2 from C:\Users\nisha\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip (python 3.12)

In [16]:
import sys
print(sys.executable)

c:\Users\nisha\AppData\Local\Programs\Python\Python314\python.exe

In [18]:
!python -m pip install imbalanced-learn

Collecting imbalanced-learn
  Using cached imbalanced_learn-0.14.2-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: numpy<3,>=1.25.2 in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from imbalanced-learn) (2.4.1)
Requirement already satisfied: scipy<2,>=1.11.4 in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from imbalanced-learn) (1.17.1)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from imbalanced-learn) (1.8.0)
Collecting sklearn-compat<0.2,>=0.1.6 (from imbalanced-learn)
  Using cached sklearn_compat-0.1.6-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: joblib<2,>=1.2.0 in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from imbalanced-learn) (3.6.0)
Using cached imbalanced_learn-0.14.2-py3-none-any.whl (236 kB)
Using cached sklearn_compat-0.1.6-py3-none-any.whl (22 kB)
Installing collected packages: sklearn-compat, imbalanced-learn

   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   ---------------------------------------- 2/2 [imbalanced-learn]

Successfully installed imbalanced-learn-0.14.2 sklearn-compat-0.1.6

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
!python -m pip install xgboost

Collecting xgboost
  Using cached xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from xgboost) (2.4.1)
Requirement already satisfied: scipy in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from xgboost) (1.17.1)
Using cached xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
!python -m pip install lightgbm catboost

Collecting lightgbm
  Using cached lightgbm-4.6.0-py3-none-win_amd64.whl.metadata (17 kB)
Collecting catboost
  Downloading catboost-1.2.10-cp314-cp314-win_amd64.whl.metadata (1.5 kB)
Requirement already satisfied: numpy>=1.17.0 in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from lightgbm) (2.4.1)
Requirement already satisfied: scipy in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from lightgbm) (1.17.1)
Collecting graphviz (from catboost)
  Using cached graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from catboost) (3.10.8)
Requirement already satisfied: pandas<4.0,>=0.24 in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from catboost) (2.3.3)
Requirement already satisfied: plotly in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from catboost) (6.5.2)
Requirement already satisfied: six in c:\users\nisha\appdata\roaming\python\python314\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\nisha\appdata\roaming\python\python314\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from matplotlib->catboost) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\nisha\appdata\roaming\python\python314\site-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from matplotlib->catboost) (12.1.0)
Requirement already satisfied: pyparsing>=3 in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from matplotlib->catboost) (3.3.1)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from plotly->catboost) (2.17.0)
Using cached lightgbm-4.6.0-py3-none-win_amd64.whl (1.5 MB)
Downloading catboost-1.2.10-cp314-cp314-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.8/101.7 MB 14.6 MB/s eta 0:00:07
   -- ------------------------------------- 6.0/101.7 MB 22.3 MB/s eta 0:00:05
   ---- ----------------------------------- 11.5/101.7 MB 23.6 MB/s eta 0:00:04
   ------ --------------------------------- 16.3/101.7 MB 23.7 MB/s eta 0:00:04
   -------- ------------------------------- 22.3/101.7 MB 24.8 MB/s eta 0:00:04
   ---------- ----------------------------- 27.3/101.7 MB 24.9 MB/s eta 0:00:03
   ------------ --------------------------- 32.5/101.7 MB 24.8 MB/s eta 0:00:03
   --------------- ------------------------ 39.1/101.7 MB 25.5 MB/s eta 0:00:03
   ----------------- ---------------------- 45.6/101.7 MB 26.0 MB/s eta 0:00:03
   -------------------- ------------------- 51.9/101.7 MB 26.3 MB/s eta 0:00:02
   ---------------------- ----------------- 58.5/101.7 MB 26.7 MB/s eta 0:00:02
   ------------------------- -------------- 65.5/101.7 MB 27.0 MB/s eta 0:00:02
   ---------------------------- ----------- 72.4/101.7 MB 27.4 MB/s eta 0:00:02
   ------------------------------ --------- 78.6/101.7 MB 27.6 MB/s eta 0:00:01
   --------------------------------- ------ 84.9/101.7 MB 27.7 MB/s eta 0:00:01
   ----------------------------------- ---- 91.0/101.7 MB 27.8 MB/s eta 0:00:01
   -------------------------------------- - 97.3/101.7 MB 27.9 MB/s eta 0:00:01
   --------------------------------------  101.7/101.7 MB 27.9 MB/s eta 0:00:01
   --------------------------------------  101.7/101.7 MB 27.9 MB/s eta 0:00:01
   ---------------------------------------- 101.7/101.7 MB 25.3 MB/s  0:00:04
Using cached graphviz-0.21-py3-none-any.whl (47 kB)
Installing collected packages: graphviz, lightgbm, catboost

   ---------------------------------------- 0/3 [graphviz]
   ------------- -------------------------- 1/3 [lightgbm]
   ------------- -------------------------- 1/3 [lightgbm]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   ---------------------------------------- 3/3 [catboost]

Successfully installed catboost-1.2.10 graphviz-0.21 lightgbm-4.6.0

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
!python -m pip install shap

Collecting shap
  Using cached shap-0.52.0-cp312-abi3-win_amd64.whl.metadata (26 kB)
Requirement already satisfied: numpy>=2 in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from shap) (2.4.1)
Requirement already satisfied: scipy in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from shap) (1.17.1)
Requirement already satisfied: scikit-learn in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from shap) (1.8.0)
Requirement already satisfied: pandas in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from shap) (2.3.3)
Requirement already satisfied: tqdm>=4.27.0 in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from shap) (4.67.3)
Requirement already satisfied: packaging>20.9 in c:\users\nisha\appdata\roaming\python\python314\site-packages (from shap) (25.0)
Collecting slicer==0.0.8 (from shap)
  Using cached slicer-0.0.8-py3-none-any.whl.metadata (4.0 kB)
Collecting numba (from shap)
  Downloading numba-0.65.1-cp314-cp314-win_amd64.whl.metadata (3.0 kB)
Collecting llvmlite (from shap)
  Downloading llvmlite-0.47.0-cp314-cp314-win_amd64.whl.metadata (5.1 kB)
Collecting cloudpickle (from shap)
  Using cached cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: colorama in c:\users\nisha\appdata\roaming\python\python314\site-packages (from tqdm>=4.27.0->shap) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\nisha\appdata\roaming\python\python314\site-packages (from pandas->shap) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from pandas->shap) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from pandas->shap) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\nisha\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas->shap) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn->shap) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\nisha\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn->shap) (3.6.0)
Using cached shap-0.52.0-cp312-abi3-win_amd64.whl (499 kB)
Using cached slicer-0.0.8-py3-none-any.whl (15 kB)
Using cached cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading llvmlite-0.47.0-cp314-cp314-win_amd64.whl (39.2 MB)
   ---------------------------------------- 0.0/39.2 MB ? eta -:--:--
    --------------------------------------- 0.5/39.2 MB 14.0 MB/s eta 0:00:03
   ---- ----------------------------------- 4.7/39.2 MB 19.0 MB/s eta 0:00:02
   --------- ------------------------------ 8.9/39.2 MB 20.1 MB/s eta 0:00:02
   ------------- -------------------------- 13.6/39.2 MB 20.8 MB/s eta 0:00:02
   ------------------ --------------------- 18.1/39.2 MB 21.2 MB/s eta 0:00:01
   ----------------------- ---------------- 23.1/39.2 MB 21.6 MB/s eta 0:00:01
   ---------------------------- ----------- 27.8/39.2 MB 21.9 MB/s eta 0:00:01
   --------------------------------- ------ 32.5/39.2 MB 22.1 MB/s eta 0:00:01
   ------------------------------------- -- 37.0/39.2 MB 22.1 MB/s eta 0:00:01
   ---------------------------------------  39.1/39.2 MB 22.1 MB/s eta 0:00:01
   ---------------------------------------  39.1/39.2 MB 22.1 MB/s eta 0:00:01
   ---------------------------------------  39.1/39.2 MB 22.1 MB/s eta 0:00:01
   ---------------------------------------- 39.2/39.2 MB 16.9 MB/s  0:00:02
Downloading numba-0.65.1-cp314-cp314-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 2.8/2.8 MB 17.9 MB/s  0:00:00
Installing collected packages: slicer, llvmlite, cloudpickle, numba, shap

   -------- ------------------------------- 1/5 [llvmlite]
   -------- ------------------------------- 1/5 [llvmlite]
   -------- ------------------------------- 1/5 [llvmlite]
   -------- ------------------------------- 1/5 [llvmlite]
   -------- ------------------------------- 1/5 [llvmlite]
   -------- ------------------------------- 1/5 [llvmlite]
   -------- ------------------------------- 1/5 [llvmlite]
   -------- ------------------------------- 1/5 [llvmlite]
   -------- ------------------------------- 1/5 [llvmlite]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   -------------------------------- ------- 4/5 [shap]
   -------------------------------- ------- 4/5 [shap]
   -------------------------------- ------- 4/5 [shap]
   -------------------------------- ------- 4/5 [shap]
   ---------------------------------------- 5/5 [shap]

Successfully installed cloudpickle-3.1.2 llvmlite-0.47.0 numba-0.65.1 shap-0.52.0 slicer-0.0.8

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import train_test_split

from imblearn.over_sampling import SMOTE

In [3]:
df = pd.read_csv(r"C:\Users\nisha\OneDrive\Desktop\Nisha\GUVI\FinalProject\BankTermDepositPrediction\Data\bank-full.csv", sep=';')
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [4]:
df['job'].value_counts()

job
blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: count, dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

In [7]:
df.shape

(45211, 17)

In [8]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [9]:
df['job'].value_counts()

job
blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: count, dtype: int64

In [4]:
df.describe()

,age,balance,day,duration,campaign,pdays,previous
count,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000
mean,40.936210,1362.272058,15.806419,258.163080,2.763841,40.197828,0.580323
std,10.618762,3044.765829,8.322476,257.527812,3.098021,100.128746,2.303441
min,18.000000,-8019.000000,1.000000,0.000000,1.000000,-1.000000,0.000000
25%,33.000000,72.000000,8.000000,103.000000,1.000000,-1.000000,0.000000
50%,39.000000,448.000000,16.000000,180.000000,2.000000,-1.000000,0.000000
75%,48.000000,1428.000000,21.000000,319.000000,3.000000,-1.000000,0.000000
max,95.000000,102127.000000,31.000000,4918.000000,63.000000,871.000000,275.000000

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [7]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [18]:
df['y'].value_counts()

y
no     39922
yes     5289
Name: count, dtype: int64

In [ ]:
df = pd.read_csv(r"C:\Users\nisha\OneDrive\Desktop\Nisha\GUVI\FinalProject\BankTermDepositPrediction\Data\bank-full.csv", sep=';')
df_copy = df.copy()

df_copy.drop('duration', axis=1, inplace=True)

# *******ENCODING for categorical variables*********
# One-hot encoding for 'job', 'marital', 'contact', 'month', 'poutcome' columns
df_copy = pd.get_dummies(df_copy,columns=['job','marital','contact','month','poutcome'],dtype='int',drop_first=True)

# Ordinal encoding for 'education' column
maping = {'unknown': 0, 'primary': 1, 'tertiary': 2, 'secondary': 3}
df_copy['education'] = df_copy['education'].map(maping)

# Label encoding for 'default', 'housing', 'loan', 'y' columns
label_encoding_cols = ['default','housing','loan', 'y']
encoder = LabelEncoder()
for col in label_encoding_cols:
    df_copy[col] = encoder.fit_transform(df_copy[col])

# ******* FEATURE ENGINNERING *********
df_copy['age_balance'] = df_copy['age'] * df_copy['balance']
df_copy['contacted_before'] = np.where(df_copy['previous'] > 0, 1, 0)
df_copy['total_loans'] = (df_copy['housing']+ df_copy['loan'])

# ******* FEATURES & TARGET VARIABLE SEPARATION *********
X = df_copy.drop('y', axis=1)
y = df_copy['y']

# ******* Scaling for numerical variables*********
scaler = RobustScaler()
numerical_cols = ['age', 'balance', 'campaign', 'pdays', 'previous']
X_scaled = scaler.fit_transform(df_copy[numerical_cols])

df_copy.head()

,age,education,default,balance,housing,loan,day,campaign,pdays,previous,...,month_may,month_nov,month_oct,month_sep,poutcome_other,poutcome_success,poutcome_unknown,age_balance,contacted_before,total_loans
0,1.266667,2,0,1.250000,1,0,5,-0.5,0.0,0.0,...,1,0,0,0,0,0,1,124294,0,1
1,0.333333,3,0,-0.308997,1,0,5,-0.5,0.0,0.0,...,1,0,0,0,0,0,1,1276,0,1
2,-0.400000,3,0,-0.328909,1,1,5,-0.5,0.0,0.0,...,1,0,0,0,0,0,1,66,0,2
3,0.533333,0,0,0.780236,1,0,5,-0.5,0.0,0.0,...,1,0,0,0,0,0,1,70782,0,1
4,-0.400000,0,0,-0.329646,0,0,5,-0.5,0.0,0.0,...,1,0,0,0,0,0,1,33,0,0